### PR TITLE
Replace rand_binom with binomrand

### LINKED ISSUE #382: rand_binom not defined
```julia
julia> using LightGraphs
INFO: Precompiling module LightGraphs...
INFO: Recompiling stale cache file /home/rluser/.julia/lib/v0.4/Rmath.ji for module Rmath.
INFO: Recompiling stale cache file /home/rluser/.julia/lib/v0.4/StatsBase.ji for module StatsBase.
INFO: Recompiling stale cache file /home/rluser/.julia/lib/v0.4/StatsFuns.ji for module StatsFuns.
ERROR: LoadError: UndefVarError: rand_binom not defined
```

I have checked StateBase, there's no such a function called rand_binom.

### PR DESCRIPTION
**Pull request by pranavtbhat**
Should fix #382. Looks like `StatsBase` renamed `rand_binom` to `binomrand`, which returns `Float64` instead of `Int`.

### CODE REVIEW

File: src/LightGraphs.jl [hunk 1]
```diff
@@ -3,7 +3,7 @@ module LightGraphs
 
 using Requires
 using GZip
-using StatsBase: rand_binom
+using StatsBase: binomrand
```
Comment (tkelman) [inline src/LightGraphs.jl]: you should update the minimum required version of StatsBase in `REQUIRE`

**Comment by tkelman** [comment]
cc @ararslan looks like we might want to upper-bound the StatsBase dependency in METADATA for existing LightGraphs tags?

**Comment by ararslan** [comment]
Sounds like a good idea.

File: REQUIRE [hunk 2]
```diff
@@ -1,7 +1,7 @@
 julia 0.4 0.5-
 Requires
 GZip 0.2.18
-StatsBase 0.7.4
+StatsBase 0.9.0
```
Comment (pranavtbhat) [inline REQUIRE]: @tkelman only `v0.9.0` has the required commit, so bumped it up all the way.

**Comment by CarloLucibello** [comment]
looks good, let's merge this. We should also tag a last 0.4 release soon

**Comment by Ward9250** [comment]
I got work from people at StatsBase:

"Please use Distributions' rand(Binomail(n,p)) for this. There is still StatsBase.binomrand but eventually it will be removed in favor of Distributions."

So it looks like `rand(Binomail(n,p))` ought to be used instead of binomrand.

**Comment by sbromberger** [comment]
I think we merge this now and then accept another PR to use Distributions.
