### PR TITLE
Bugfix/#1251

### LINKED ISSUE #1251: [BUG] incidence_matrix can produce invalid instances of SparseMatrixCSC
**Description of bug**
The function `incidence_matrix` can produce matrices that do not conform to the SparseMatrixCSC type assumption that the entries in the `rowval` field of a sparse matrix are sorted by column.  As a result, arithmetic operations involving outputs of `incidence_matrix` can be incorrect.  The assumptions on the sparse type are listed at the top of

> `julia/stdlib/SparseArrays/src/sparsematrix.jl`

and the relevant assumption is
```julia

# Assumes that row values in rowval for each column are sorted
#      issorted(rowval[colptr[i]:(colptr[i+1]-1)]) == true

```
This assumption appears in all Julia versions from 1.0 on, including `master`.

**How to reproduce**
```julia

julia> using LightGraphs

julia> A = incidence_matrix(path_digraph(3))
3×2 SparseArrays.SparseMatrixCSC{Int64,Int64} with 4 stored entries:
  [1, 1]  =  -1
  [2, 1]  =  1
  [2, 2]  =  -1
  [3, 2]  =  1

julia> B = incidence_matrix(reverse(path_digraph(3)))
3×2 SparseArrays.SparseMatrixCSC{Int64,Int64} with 4 stored entries:
  [2, 1]  =  -1
  [1, 1]  =  1
  [3, 2]  =  -1
  [2, 2]  =  1

julia> A + B
3×2 SparseArrays.SparseMatrixCSC{Int64,Int64} with 4 stored entries:
  [1, 1]  =  -1
  [1, 1]  =  1
  [2, 2]  =  -1
  [2, 2]  =  1

julia> Matrix(A + B)
3×2 Array{Int64,2}:
 1  0
 0  1
 0  0

julia> Matrix(A)
3×2 Array{Int64,2}:
 -1   0
  1  -1
  0   1

julia> Matrix(B)
3×2 Array{Int64,2}:
  1   0
 -1   1
  0  -1

julia> Matrix(A) + Matrix(B)
3×2 Array{Int64,2}:
 0  0
 0  0
 0  0

```

**Expected behavior**
Because `reverse` does not change the order of the vertices or edges, the incidence matrices `A` and `B` should be the same except for the sign, that is, `A+B` should be the zero matrix regardless of whether they are added as sparse matrices or first converted to dense matrices and then added.

**Actual behavior**
`B` is not a valid SparseMatrixCSC instance because it lists its nonzero entries in the wrong order.  Thus `A+B` does not produce a sparse zero matrix but rather an invalid sparse matrix with duplicate values that add up to zero.  Hence converting this sparse sum to dense via `Matrix(A+B)` does not yield the expected zero matrix.  In contrast, `Matrix(A)` and `Matrix(B)` produce the correct dense versions of the incidence matrices, and the sum of these dense versions is zero as expected.

**Version information**
 ```julia

julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 5 2600 Six-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, znver1)

(v1.2) pkg> status LightGraphs
    Status `~/.julia/environments/v1.2/Project.toml`
  [093fc24a] LightGraphs v1.3.0

```

### PR DESCRIPTION
**Pull request by jpfairbanks**
I think this fixes #1251. We just needed to sort the outneighbors as we build the matrix. And then swap nzval for edges that are "upside down".

### CODE REVIEW

File: src/linalg/spectral.jl [hunk 1]
```diff
@@ -151,13 +151,22 @@ function incidence_matrix(g::AbstractGraph, T::DataType=Int; oriented=false)
     # every col has the same 2 entries
     colpt = collect(1:2:(nz + 1))
     nzval = repeat([(isdir || oriented) ? -one(T) : one(T), one(T)], n_e)
+    swap(i,j) = begin
+        tmp = nzval[i]
+        nzval[i] = nzval[j]
+        nzval[j] = tmp
+    end
```
Comment (sbromberger) [inline src/linalg/spectral.jl]: why can't we just do
```
nzval[i], nzval[j] = nzval[j], nzval[i]
```
and eliminate the need for `tmp`?

```
julia> a = 3
3

julia> b = 10
10

julia> a, b, = b, a
(10, 3)

julia> a
10

julia> b
3
```

Comment (sbromberger) [reply src/linalg/spectral.jl]: You do this below :)

File: src/linalg/spectral.jl [hunk 2]
```diff
@@ -151,13 +151,22 @@ function incidence_matrix(g::AbstractGraph, T::DataType=Int; oriented=false)
...
 
     # iterate over edges for row indices
     rowval = zeros(Int, nz)
     i = 1
-    for u in vertices(g)
-        for v in outneighbors(g, u)
+    for u in sort(vertices(g))
```
Comment (sbromberger) [inline src/linalg/spectral.jl]: `vertices(g)` is sorted by default for all SimpleGraphs. We make this assumption throughout the codebase so I'm not sure we need an explicit sort here.

File: src/linalg/spectral.jl [hunk 3]
```diff
@@ -151,13 +151,22 @@ function incidence_matrix(g::AbstractGraph, T::DataType=Int; oriented=false)
...
+        for v in sort(outneighbors(g, u))
```
Comment (sbromberger) [inline src/linalg/spectral.jl]: `outneighbors` is similarly sorted.

File: src/linalg/spectral.jl (hunk 1 above)
Comment (jpfairbanks) [reply src/linalg/spectral.jl]: I did it with values, does that work with vectors? I'm thinking like a C programmer.

File: src/linalg/spectral.jl (hunk 2 above)
Comment (jpfairbanks) [reply src/linalg/spectral.jl]: vertices is always a 1:n right? The compiler will optimize it out, but it will definitely break if we ever relax that assumption.

File: src/linalg/spectral.jl (hunk 3 above)
Comment (jpfairbanks) [reply src/linalg/spectral.jl]: If outneighbors is already sorted then this bug shouldn't happen? unless it is only the v<u case that causes the problem?

File: src/linalg/spectral.jl (hunk 1 above)
Comment (sbromberger) [reply src/linalg/spectral.jl]:
```
julia> a = [1,2,3,4,5]
5-element Array{Int64,1}:
 1
 2
 3
 4
 5

julia> a[3], a[5] = a[5], a[3]
(5, 3)

julia> a
5-element Array{Int64,1}:
 1
 2
 5
 4
 3
```

File: src/linalg/spectral.jl (hunk 2 above)
Comment (sbromberger) [reply src/linalg/spectral.jl]: Nice:

```
sort(r::AbstractUnitRange) = r
```

File: src/linalg/spectral.jl (hunk 3 above)
Comment (sbromberger) [reply src/linalg/spectral.jl]: `outneighbors` is definitely already sorted, since the `fadjlist` is created in sorted order.
