### PR TITLE
fixes #467, adds an assert for edge counts, and includes tests

### LINKED ISSUE #467: Bug with creating graph from digraph with self loops
```
julia> g = DiGraph(3)
{3, 0} directed graph

julia> add_edge!(g,1,1)
true

julia> add_edge!(g,1,2)
true

julia> collect(edges(g))
2-element Array{Pair{Int64,Int64},1}:
 1=>1
 1=>2

julia> h = Graph(g)
{3, 1} undirected graph

julia> collect(edges(h))
ERROR: BoundsError: attempt to access 1-element Array{Pair{Int64,Int64},1} at index [2]
 in copy!(::Array{Pair{Int64,Int64},1}, ::LightGraphs.EdgeIter) at ./abstractarray.jl:479
 in collect(::LightGraphs.EdgeIter) at ./array.jl:273
```

### PR DESCRIPTION
**Pull request by sbromberger**
Fixes for creating graphs / digraphs from other graphs / digraphs with self-loops.

deprecates `has_self_loop` in favor of `has_self_loops`; adds `num_self_loops` to get an actual count.

### CODE REVIEW

File: src/core.jl [hunk 1]
```diff
@@ -253,5 +253,11 @@ neighbors(g::SimpleGraph, v::Int) = out_neighbors(g, v)
 "Returns the neighbors common to vertices `u` and `v` in `g`."
 common_neighbors(g::SimpleGraph, u::Int, v::Int) = intersect(neighbors(g,u), neighbors(g,v))
 
+@deprecate has_self_loop has_self_loops
+
 "Returns true if `g` has any self loops."
-has_self_loop(g::SimpleGraph) = any(v->has_edge(g, v, v), vertices(g))
+
```
Comment (CarloLucibello) [inline src/core.jl]: there should be no whiteline beetween a function and its docstring, otherwise the string doesn't count as docstring I think

Comment (sbromberger) [inline src/core.jl]:
```
help?> has_self_loops
search: has_self_loops has_self_loop

  Returns true if g has any self loops.
```
